# Generated by Django 6.0 on 2026-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('ORG', 'Organization'), ('ADMIN', 'Admin')], default='DONOR', max_length=10),
        ),
    ]
