# Generated by Django 6.0 on 2026-01-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='current_amount',
            new_name='collected_amount',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.organization'),
        ),
    ]
