# Generated by Django 6.0 on 2026-01-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_approved_at_campaign_approved_by_and_more'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
