# Generated by Django 6.0 on 2026-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_campaign_alter_donation_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
